### ISSUE TITLE
Using a `createAsyncSaga` wrapped saga with a rootSaga/call method

### ISSUE THREAD

**Issue by lawoollett** [franckLdx/create-async-saga#2]
This I don't believe is a bug but more a request for guidance, when wrapping a saga in the `createAsyncSaga` utility, I would like to call it in the watch task/root saga. For example:

```
import { all, call } from "redux-saga/effects";
import { createAsyncSaga } from "create-async-saga";
import { getRemoteTestData } from "api";

export const onFetchTestData = createAsyncSaga("test/fetch", function* () {
  const testData = yield getRemoteTestData();
  if (!testData) {
    throw new Error("There was an empty response");
  }
  return testData;
});

export function* testSaga() {
  yield all([
    call(onFetchTestData.asyncSaga),
  ]);
}
```

Typescript errors with:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '({ payload, meta }: PayloadAction<void, string, { requestId: string; }, never>) => Generator<any, void, any>' is not assignable to parameter of type '{ context: unknown; fn: (this: unknown, ...args: any[]) => any; }'.
      Type '({ payload, meta }: PayloadAction<void, string, { requestId: string; }, never>) => Generator<any, void, any>' is missing the following properties from type '{ context: unknown; fn: (this: unknown, ...args: any[]) => any; }': context, fn
```
Is there a better way of doing this, calling a wrapped saga manually rather than in response to an action (using take).

**Comment by franckLdx** [comment]
This has nothing related to create-async-saga.

redux-saga defies 2 type of sgas: watcher and worker.:https://redux-saga.js.org/docs/Glossary/#watcherworker
A worker saga responses to an action, and is not meant to be called manually.
In a root saga you can have `yield all([
    call(watcherSaga)
  ]);
}`

To test your saga, pick one of the tools in https://redux-saga.js.org/docs/advanced/Testing#testing-libraries


PS: In the exemple `const testData = yield getRemoteTestData();` should be `const testData = yield call(getRemoteTestData);`
